spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  jwt:
    secretKey: ${JWT_SECRET}
    header: ${HEADER}
    prefix: ${PREFIX}
    accessExp: ${ACCESS_EXP}

  main:
    allow-bean-definition-overriding: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
      post-images : ${POST_IMAGES_FOLDER}
      preview-images : ${PREVIEW_IMAGES_FOLDER}
      profile-images: ${PROFILE_IMAGES_FOLDER}
      url: ${S3_URL}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}