name: dev branch auto ci process script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            # 기존 폴더 삭제 후 새로 클론
            rm -rf /home/ubuntu/Server-V2
            git clone -b main https://github.com/Team-jeong-ho-kim/Sillok_BE.git /home/ubuntu/Server-V2

            cd /home/ubuntu/Server-V2
            npm install --force
            npm run build || exit 1

            pm2 stop all || true
            pm2 delete all || true
            pm2 start dist/main.js
