name: dev branch auto ci process script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            # 서버에 프로젝트 디렉토리 없으면 클론
            if [ ! -d "/home/ubuntu/Server-V2" ]; then
              git clone https://github.com/Team-jeong-ho-kim/Sillok_BE.git /home/ubuntu/Server-V2
            fi

            cd /home/ubuntu/Server-V2
            git pull origin dev
            npm install --force
            npm run build

            # PM2 프로세스 삭제 후 재시작
            pm2 stop all || true
            pm2 delete all || true
            pm2 start dist/main.js
